version: "3"

services:
  golang:
    build:
      context: .
    container_name: ${PROJECT_NAME}
    restart: always
    environment:
      - ENV = local
      - PROJECT_NAME = ${PROJECT_NAME}
    depends_on:
      - mysql
    working_dir: /go/src/mini-news
    networks:
      - web_service
    volumes:
      - .:/go/src/mini-news
    labels:
      - "traefik.http.routers.golang-${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.local.com`)"
      - "traefik.http.services.golang-${PROJECT_NAME}.loadbalancer.server.port=8080"
    command: "fresh runner.conf"
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    restart: always
    volumes:
      - /home/winston/DB/mini-news:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mininews
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks:
      - web_service
  redis:
    image: redis:5.0.8
    container_name: ${PROJECT_NAME}-redis
    sysctls:
      net.core.somaxconn: 1024
    restart: always
    volumes:
      - ./Redis/${PROJECT_NAME}:/data
      - ./redis-conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - web_service

networks:
  web_service:
    external: true